import type { UniqueEntityId } from "../value-object/unique-entity-id";

/**
 * Base entity: has identity and is compared by identity (not by attributes). Props are
 * held read-only; the identity is supplied at construction (never generated by the domain).
 */
export abstract class Entity<TProps> {
  protected readonly props: TProps;
  protected readonly _id: UniqueEntityId;

  protected constructor(props: TProps, id: UniqueEntityId) {
    this.props = props;
    this._id = id;
  }

  get id(): UniqueEntityId {
    return this._id;
  }

  equals(other?: Entity<TProps>): boolean {
    if (other === null || other === undefined) return false;
    if (this === other) return true;
    if (!(other instanceof Entity)) return false;
    return this._id.equals(other._id);
  }
}
